version: '3'
services:
  graph-node:
    image: >-
      graphprotocol/graph-node:v0.11.0
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
    links:
      - ipfs
      - postgres
      - ganache
    environment:
      postgres_host: 'postgres:5432'
      postgres_user: postgres
      postgres_pass: letmein
      postgres_db: postgres
      ipfs: 'ipfs:5001'
      ethereum: 'development:http://ganache:8545'
  ipfs:
    build: docker/ipfs
    ports:
      - '5001:5001'
    logging:
      driver: none
  postgres:
    build: docker/postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: letmein
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - '8545:8545'
    command: -m "myth like bonus scare over problem client lizard pioneer submit female collect"
